### PR TITLE
Fix architecture issue when building on m1 for iOS simulator

### PR DESCRIPTION
**Pull request by DmitriyKirakosyan**
* [ ] Has `CHANGELOG.md` been updated?
* [ ] Are tests passing locally?
* ~[ ] Are the files formatted correctly?~
* ~[ ] Did you add unit tests?~
* [x] Did you test your change with the sample apps?

## Description

This PR fixes the following build errors if building on mac m1 for ios simulator:
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_MSPLCrashReporter", referenced from:
      objc-class-ref in AppCenterCrashes(MSACCrashes.o)
  "_OBJC_CLASS_$_MSPLCrashReport", referenced from:
      objc-class-ref in AppCenterCrashes(MSACCrashes.o)
  "_OBJC_CLASS_$_MSPLCrashReporterConfig", referenced from:
      objc-class-ref in AppCenterCrashes(MSACCrashes.o)
ld: symbol(s) not found for architecture arm64

```

## Related PRs or issues

[AB#86888](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/86888)
https://github.com/microsoft/appcenter-sdk-apple/issues/1621

### CODE REVIEW

**Review by MatkovIvan — CHANGES_REQUESTED** [review]
As far as I remember, this won't work properly without moving to XCF in CocoaPods, which is blocked by https://github.com/CocoaPods/CocoaPods/issues/10262

**Comment by DmitriyKirakosyan** [comment]
@MatkovIvan I've tested the changes with cocoapods locally and it worked for me. What I did is:
- Built 'CrashReporter' scheme from my branch and zipped the output frameworks
- Added a local podspec file with reference to that zip file
- Created an empty ios app and added Podfile with reference to the local podspec file
- Ran "pod install" and built the app

The app launched on a real device and on emulator.

Do you have a specific steps that I could use to reproduce the issue you pointed out?

**Comment by DmitriyKirakosyan** [comment]
@MatkovIvan The issue was in Carthage integration.
Original PLCR issue: https://github.com/microsoft/plcrashreporter/issues/131
FIx in PLCR: https://github.com/microsoft/plcrashreporter/pull/132
Carthage issue: https://github.com/Carthage/Carthage/issues/3146

Additionally, it works on CI without the changes in this PR, so release frameworks are not affected by the issue.

Closing this PR, as it breaks the carthage integration.

**Comment by DmitriyKirakosyan** [comment]
Reopening this PR as we new distribute binaries via Carthage, so the fix can be applied without breaking any integration.
cc @MatkovIvan

**Comment by MatkovIvan** [comment]
I still have some doubts. Many customers use no binaries flag for Carthage.

**Comment by DmitriyKirakosyan** [comment]
@MatkovIvan It should be enough to document this issue, like we did for the AppCenter SDK here: https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/ios#32-integration-via-carthage.

The workaround page: https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md

The workaround for Xcode 12 is actually a workaround for our issue, as it reads:
> Well, shortly, Carthage builds fat frameworks, which means that the framework contains binaries for all supported architectures. Until Apple Silicon was introduced it all worked just fine, but now there is a conflict as there are duplicate architectures (arm64 for devices and arm64 for simulator). This means that Carthage cannot link architecture specific frameworks to a single fat framework.

What do you think?

**Comment by MatkovIvan** [comment]
Ok, sounds good 👍

**Review by AnastasiaKubova — DISMISSED** [review]

**Review by AnastasiaKubova — APPROVED** [review]

**Pull request merged**
