### PR TITLE
Add missing cleaning of mobjects

### PR DESCRIPTION
**Pull request by MatkovIvan**
* [x] Has `CHANGELOG.md` been updated?
* [x] Are tests passing locally?
* [x] Are the files formatted correctly?
* [ ] Did you add unit tests?
* [x] Did you test your change with the sample apps?

## Description

Fix memory leaks by adding missing cleaning of mobjects.

## Related PRs or issues

#171
[AB#85837](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/85837)

### CODE REVIEW

**Review by DmitriyKirakosyan — APPROVED** [review]
Works for me!

**Comment by gestrich** [comment]
@MatkovIvan Hi - I tried the fix and it seemed to work well -- no crashes or logs regarding memory issues. Thank you for fixing. 

Any chance a patch version 1.8.2 can be released with this change? That would allow clients to get this important fix now that depend on the 1.8.x series (i.e. AppCenter). If not, any ideas when he next PLCrashReporter minor version will be released that will include this? If it may be delayed, we were going to cherry-pick just the memory fix commit in this PR and use a fork of AppCenter that uses that.

**Comment by MatkovIvan** [comment]
Hey. There is no specific ETA for the next release, most likely - end of this quarter. Sorry for inconvenience.

BTW next version will be 1.9.0 instead of 1.8.2, because of already merged feature.

**Comment by gestrich** [comment]
Ok sounds good - thanks.

**Comment by gestrich** [comment]
@MatkovIvan  In that case you do you see any harm in us cherrypicking the memory fix commit (610ecb6188d3aff6f14bea2941e9d53ec081653b) and applying that directly to our fork of 1.8.1? I didn't get conflicts doing so so it seems like a targeted change that can be aplied.

**Comment by MatkovIvan** [comment]
Yep, it should be fine

**Pull request merged**
