### PR TITLE
Use public API to set reply msgh_id for iOS

### PR DESCRIPTION
**Pull request by LinyiWu**
* [ ] Has `CHANGELOG.md` been updated?
* [x] Are tests passing locally?
* [x] Are the files formatted correctly?
* [ ] Did you add unit tests?
* [ ] Did you test your change with the sample apps?

## Description

Use public API mig_reply_setup() to set mach exception reply msgh_id.

### CODE REVIEW

**Comment by DmitriyKirakosyan** [comment]
Hi @LinyiWu , thank you for the contribution!

The public API would also set other properties, which we then will override. It would make sense to remove these lines as we set the same values:
```
OutP->Head.msgh_local_port  = MACH_PORT_NULL;
OutP->NDR = NDR_record;
```

We set different values for `msgh_remote_port` and `size` though.

Could you clarify why do you think that using public API makes more sense here?

**Comment by LinyiWu** [comment]
For `msgh_id`, I think the public API makes more sense than original magic offset 100. For other properties, they may be set differently in future OS releases. `msgh_id` is the only property I care about.
Or should I
```
mig_reply_setup((mach_msg_header_t *) request, (mach_msg_header_t *) &reply);
mach_msg_id_t reply_id = reply.Head.msgh_id;
memset(&reply, 0, sizeof(reply));
reply.Head.msgh_id = reply_id;
```

**Comment by DmitriyKirakosyan** [comment]
@LinyiWu I would not touch this code if it works correctly. This code hasn't changed since it was added 10 years ago.
The system file `mig_reply_setup.c` doesn't seem to be ever changed to me. Even if it changes, it will affect our implementation as you propose to rely on this method.
I personally prefer to keep things as they are, except you have a strong argument for it.

**Comment by DmitriyKirakosyan** [comment]
I'm closing this for now.

**Pull request closed without merging**
